[features]
seeds = false
[programs.devnet]
mint_nft = "HcD68wywC1ftgAmCkixFG41e1V2JAR3pcv7o9R4eQJ1t"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/foxylady/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
